// Bump the project version in every file that has its own copy.
//
// Usage:
//   pnpm sync-version 1.0.1
//
// Updates:
//   package.json                                   -> "version"
//   src-tauri/tauri.conf.json                      -> "version" + bundle.android.versionCode
//   src-tauri/gen/android/app/tauri.properties     -> versionName + versionCode
//                                                     (skipped if the file is
//                                                      missing - it is
//                                                      regenerated by Tauri on
//                                                      the next android build)
//
// bundle.android.versionCode pins what the Tauri CLI's own Android project
// generator writes into tauri.properties on every `tauri android build` -
// without it, the generator falls back to its own semver-derived formula and
// silently discards this script's versionCode.
//
// versionCode packs the semver into decimal fields with a 4-digit slot:
//   versionCode = major * 1e8 + minor * 1e6 + patch * 1e4 + slot
// Slots: 1-4499 phone beta, 4501-8999 TV beta (ordinal + 4500),
// 9000 phone stable, 9500 TV stable (gradle adds 500 on XTREAM_TV_BUILD).
// Caps: major <= 20 (Play's 2.1e9 limit), minor/patch <= 99.

import { readFileSync, writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")

const version = process.argv[2]
if (!version || !/^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/.test(version)) {
  console.error(`Usage: pnpm sync-version <x.y.z[-prerelease]>`)
  console.error(`Got: ${process.argv[2] ?? "(nothing)"}`)
  process.exit(1)
}

const pkgPath = path.join(ROOT, "package.json")
const tauriConfPath = path.join(ROOT, "src-tauri", "tauri.conf.json")
const androidPath = path.join(ROOT, "src-tauri", "gen", "android", "app", "tauri.properties")

const [major, minor, patch] = version.split("-")[0].split(".").map(Number)
if (major > 20 || minor > 99 || patch > 99) {
  console.error(`Version ${version} exceeds the versionCode field caps (major <= 20, minor/patch <= 99)`)
  process.exit(1)
}
const versionCode = major * 100_000_000 + minor * 1_000_000 + patch * 10_000 + 9000

patchJsonVersion(pkgPath, "package.json")
patchJsonVersion(tauriConfPath, "src-tauri/tauri.conf.json")

patchTauriConfVersionCode(tauriConfPath, versionCode)

let androidRaw = null
try {
  androidRaw = readFileSync(androidPath, "utf8")
} catch (err) {
  if (err?.code !== "ENOENT") throw err
}

if (androidRaw !== null) {
  if (!/tauri\.android\.versionCode=\d+/.test(androidRaw) || !/tauri\.android\.versionName=/.test(androidRaw)) {
    console.error(`Could not find versionName/versionCode in ${androidPath}`)
    process.exit(1)
  }
  const patched = androidRaw
    .replace(/tauri\.android\.versionName=[^\r\n]*/, `tauri.android.versionName=${version}`)
    .replace(/tauri\.android\.versionCode=\d+/, `tauri.android.versionCode=${versionCode}`)
  writeFileSync(androidPath, patched)
  console.log(`src-tauri/gen/android/app/tauri.properties -> ${version} (versionCode ${versionCode})`)
} else {
  console.log(`src-tauri/gen/android/app/tauri.properties: not found, skipping`)
  console.log(`  (Tauri will regenerate it on the next \`pnpm tauri:android\` build,`)
  console.log(`   using versionCode ${versionCode} derived from tauri.conf.json)`)
}

function patchTauriConfVersionCode(file, versionCode) {
  const raw = readFileSync(file, "utf8")
  const existing = /"android"\s*:\s*\{[^}]*"versionCode"\s*:\s*\d+/
  if (existing.test(raw)) {
    const patched = raw.replace(
      /("android"\s*:\s*\{[^}]*"versionCode"\s*:\s*)\d+/,
      `$1${versionCode}`,
    )
    writeFileSync(file, patched)
    console.log(`src-tauri/tauri.conf.json -> bundle.android.versionCode ${versionCode}`)
    return
  }
  const insertionPoint = /("createUpdaterArtifacts"\s*:\s*true,\n)/
  if (!insertionPoint.test(raw)) {
    console.error(`Could not find an insertion point for bundle.android.versionCode in ${file}`)
    process.exit(1)
  }
  const patched = raw.replace(
    insertionPoint,
    `$1    "android": {\n      "versionCode": ${versionCode}\n    },\n`,
  )
  writeFileSync(file, patched)
  console.log(`src-tauri/tauri.conf.json -> bundle.android.versionCode ${versionCode} (added)`)
}

function patchJsonVersion(file, label) {
  const raw = readFileSync(file, "utf8")
  if (!/"version"\s*:\s*"\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?"/.test(raw)) {
    console.error(`Could not find a "version": "x.y.z" line in ${file}`)
    process.exit(1)
  }
  const patched = raw.replace(
    /("version"\s*:\s*")\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(")/,
    `$1${version}$2`,
  )
  writeFileSync(file, patched)
  console.log(`${label} -> ${version}`)
}
